### ISSUE TITLE
API is not reachable - MacOS

### ISSUE THREAD

**Issue by pdestrais** [iongion/podman-desktop-companion#100]
Hi,

Podman commands are running fine, a podman machine is started but I can't connect using podman-desktop-companion.
I get 'API not reachable' when I test the connection (the socket file in the connection string exists on my disk). From the logs, the query of the socket is going in timeout.
How can I determine the connection string for my podman machine ? 

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/11016696/181794535-d1642dff-0c34-40dd-a67a-36782ba5e68e.png">

**Comment by iongion** [comment]
Can you copy paste that curl command to your terminal and reply with the
output? Thanks

**Comment by pdestrais** [comment]
Here is the output :

curl -v -X GET --unix-socket "/Users/pdestrais/.local/share/containers/podman/machine/podman-machine-default/podman.sock" "http://d/v3.0.0/libpod/_ping" -H "Accept: application/json" -H "Content-Type: application/json"

Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying /Users/pdestrais/.local/share/containers/podm:0...
* Connected to d (/Users/pdestrais/.local/share/containers/podm) port 80 (#0)
> GET /v3.0.0/libpod/_ping HTTP/1.1
> Host: d
> User-Agent: curl/7.79.1
> Accept: application/json
> Content-Type: application/json
> 
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server

**Comment by iongion** [comment]
Thanks, what about this:

```
curl -i -v --unix-socket "/Users/pdestrais/.local/share/containers/podman/machine/podman-machine-default/podman.sock" "http://d/v3.0.0/libpod/_ping" -H "Accept: application/json" -H "Content-Type: application/json"
```

**Comment by pdestrais** [comment]
Same result :-(

**Comment by iongion** [comment]
Can you take a screenshot ? I want to see the status codes and headers please

**Comment by iongion** [comment]
This is how it looks for me on linux (using podman machine)

```
curl -i -v --unix-socket "/home/istoica/.local/share/containers/podman/machine/podman-machine-default/podman.sock" "http://d/v3.0.0/libpod/_ping" -H "Accept: application/json" -H "Content-Type: application/json"
*   Trying /home/istoica/.local/share/containers/podman/:0...
* Connected to d (/home/istoica/.local/share/containers/podman/) port 80 (#0)
> GET /v3.0.0/libpod/_ping HTTP/1.1
> Host: d
> User-Agent: curl/7.84.0
> Accept: application/json
> Content-Type: application/json
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Api-Version: 1.40
Api-Version: 1.40
< Builder-Version: 
Builder-Version: 
< Buildkit-Version: 
Buildkit-Version: 
< Cache-Control: no-cache
Cache-Control: no-cache
< Docker-Experimental: true
Docker-Experimental: true
< Libpod-Api-Version: 4.1.0
Libpod-Api-Version: 4.1.0
< Libpod-Buildah-Version: 1.26.1
Libpod-Buildah-Version: 1.26.1
< Pragma: no-cache
Pragma: no-cache
< Server: Libpod/4.1.0 (linux)
Server: Libpod/4.1.0 (linux)
< X-Reference-Id: 0xc000bc2640
X-Reference-Id: 0xc000bc2640
< Date: Mon, 01 Aug 2022 06:27:39 GMT
Date: Mon, 01 Aug 2022 06:27:39 GMT
< Content-Length: 2
Content-Length: 2
< Content-Type: text/plain; charset=utf-8
Content-Type: text/plain; charset=utf-8

< 
* Connection #0 to host d left intact
OK
```

**Comment by pdestrais** [comment]
<img width="1665" alt="image" src="https://user-images.githubusercontent.com/11016696/182086373-25088dbb-c8c4-4a8c-ae70-5e36b4782327.png">

**Comment by iongion** [comment]
Seem you might have some trouble with the podman machine.

You can try to re-create and update the podman machine for maybe different outcome

```
podman machine stop
podman machine rm
podman machine init
```

**Comment by pdestrais** [comment]
You were right, my podman machine had an issue. After removing and creating a new one, everything is fine now. Thank you for your quick support !!

**Comment by iongion** [comment]
Glad it helped, closing the issue.
