### ISSUE TITLE
Newlines do not display correctly in logs

### ISSUE THREAD

**Issue by Sanqui** [iongion/podman-desktop-companion#103]
Versions:
- Podman Destkop Companion GUI v4.1.0-rc.28.p
- CLI podman 4.2.1
- OS Fedora 36

Steps to reproduce:
1. Launch Podman Desktop Companion
2. Run `podman run hello-world`
3. Under Containers, locate the hello-world container and open logs

Newlines do not display correctly in the logs.  Erroneous control characters are displayed instead.

Screenshot:
![image](https://user-images.githubusercontent.com/289437/197753124-6b533657-dbe3-42ae-bc8e-bb055693fbb8.png)

Should look like:
```
!... Hello Podman World ...!

         .--"--.           
       / -     - \         
      / (O)   (O) \        
   ~~~| -=(,Y,)=- |         
    .---. /`  \   |~~      
 ~/  o  o \~~~~.----. ~~   
  | =(X)= |~  / (O (O) \   
   ~~~~~~~  ~| =(Y_)=-  |   
  ~~~~    ~~~|   U      |~~ 

Project:   https://github.com/containers/podman
Website:   https://podman.io
Documents: https://docs.podman.io
Twitter:   @Podman_io
```

**Comment by iongion** [comment]
Solved in [5.2.0-rc.2](https://github.com/iongion/podman-desktop-companion/releases/tag/5.2.0-rc.2)
