### ISSUE TITLE
Linux / OpenSuse / Flatpak : rootless podman socket not found

### ISSUE THREAD

**Issue by kwaltzer** [iongion/podman-desktop-companion#109]
On my system (OpenSuse Tumbleweed), the podman socket is exposed on the host as /run/user/1000/podman/podman.sock (as I'm $UID = 1000)

When running podman desktop companion in a flatpak, it doesn't have the rights to access this fileystem, and such complains that the API is not reachable.

The following command fixed the problem for me : `flatpak override --user --filesystem=xdg-run/podman io.github.iongion.PodmanDesktopCompanion`

Maybe could this permission be in included the flatpak manifest ?

**Comment by iongion** [comment]
Thanks, it is now in master, it will be in `5.2.0-rc.4` after some testing
