### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by trymeouteh** [iongion/podman-desktop-companion#115]
There has not been a release since 2022.

**Comment by mailinglists35** [comment]
looks like author got cold feet on this project particularly. he does seem to have had activity in other places on github, but not here.

https://github.com/iongion?tab=overview&from=2023-10-01&to=2023-10-31

**Comment by xlat** [comment]
I found another project still active: https://github.com/containers/podman-desktop

**Comment by TomSweeneyRedHat** [comment]
As others noted, I don't think this project has had a lot of activity over the past year or two.  However, as @xlat pointed out, the [Podman Desktop](https://podman-desktop.io/) project is very active and growing on [GitHub](https://github.com/containers/podman-desktop).

**Comment by Malix-off** [comment]
https://github.com/iongion/podman-desktop-companion/issues/119

**Comment by iongion** [comment]
@TomSweeneyRedHat if you agree with these changes <https://github.com/iongion/podman-desktop-companion/pull/120/files> to clarify, let's merge - I don't want to archive it, it makes no sense, but I do understand the effort to avoid confusion, of 4 users.

**Comment by iongion** [comment]
Done - released `5.2.0-rc.1`, thank you all guys and wish you to be awesome.

**Comment by iongion** [comment]
@trymeouteh - it is alive when I have time. See home page and README.md notes.
