### ISSUE TITLE
[ARCHIVE REQUEST] podman-desktop

### ISSUE THREAD

**Issue by Malix-off** [iongion/podman-desktop-companion#119]
Please archive in favor of https://github.com/containers/podman-desktop

Also see #115

**Comment by iongion** [comment]
Hi Malix, I won't archive the project as I take a lot of pride in it and I still use it.
But I did create a PR to clarify and encourage people to use the official UI.

See here <https://github.com/iongion/podman-desktop-companion/pull/120/files>

**Comment by Malix-off** [comment]
Understandable, thanks !
