### ISSUE TITLE
Feature request: Add homebrew installation support

### ISSUE THREAD

**Issue by dm3ch** [iongion/podman-desktop-companion#17]

**Comment by iongion** [comment]
Do you guys have some examples of GUI apps distributed with homebrew ?

**Comment by iongion** [comment]
Closing this for now, I don't think I am able to add homebrew support for GUI apps, I tried to find one but was unable.
I do have a hurdle right now to get it properly digitally signed, but I need an apple developer account first.
Feel free to reopen if you are able to find more info.

**Comment by plessbd** [comment]
> Do you guys have some examples of GUI apps distributed with homebrew ?

you want to use [homebrew-cask](https://github.com/Homebrew/homebrew-cask)

here is [firefox](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/firefox.rb) as an example
