### ISSUE TITLE
MacOS Montery : Automatic detection failed

### ISSUE THREAD

**Issue by ksingh7** [iongion/podman-desktop-companion#19]
Hi @iongion  i have read through the issue #14  before raising this issue. I am facing same issue as mentioned in #14  but this time for MacOS Monterey 

Can you help ?

Thanks for developing this app

![image](https://user-images.githubusercontent.com/9701902/156024717-013e8017-f02c-4703-b4a0-a6eb222fdc1b.png)

**Comment by iongion** [comment]
Hi, only podman through lima is supported on macos for now, wip for podman
machine support

**Comment by will-hu-0** [comment]
Same issue here..I am using macOS Monterey 12.3
![image](https://user-images.githubusercontent.com/4235291/158773391-ee96b2e7-aeb6-49dd-9b67-10eb30ece134.png)

**Comment by iongion** [comment]
@will-hu-0 I am sorry for your experience, I am working on having true podman machine support these days for both windows and mac and will make it much easier.

Same recommendation meanwhile, you need to install LIMA as only that works in this version for mac.

**Comment by iongion** [comment]
Good news, just got it working with native podman `4.0.3`

![image](https://user-images.githubusercontent.com/867609/162325710-75be8ef0-3df7-44ec-accf-b5a2f2be8155.png)

I am re-writing all the detection part of how podman execution should be decided, the guys did an amazing job with the 4.x series, will release a minor version for this

**Comment by iongion** [comment]
"Hypervisor" is actually `podman machine init` and then grabbing the socket

**Comment by iongion** [comment]
There is a new release for MacOS that does not require or support lima for now, give it a try
