### ISSUE TITLE
New podman version support

### ISSUE THREAD

**Issue by jsanta** [iongion/podman-desktop-companion#23]
Hi. Due to project requirements had to stop  testing this great app, and podman released a new version.
It's supposed to support volume mounting on machine initialization, by adding the -v param:
`podman machine init -v /opt:/var/mnt/opt `
where` /opt` is my local `/opt` folder and `/var/mnt/opt` is the "_remote_" mounting folder (which has to use a physical path, sym links won't work).

Works almost flawlessly, recovered some old mysql data files from a docker machine with this. Besides some file movement and permission changes I had to do, everything worked.

Is _podman-only_ support planned in any future versions? I mean currently podman-desk-companion works with lima created machines, which support  folder mounting; but now  podman does support folder mounting with less problems.

Best regards.

**Comment by iongion** [comment]
Hi @jsanta , sorry for your experience, I do have a version working that I did not push yet, which has optional lima or native, I am rushing things as much as I can due to real job.

**Comment by iongion** [comment]
Have a look, just released 4.x support
