### ISSUE TITLE
Release as Flatpak

### ISSUE THREAD

**Issue by sebasmonia** [iongion/podman-desktop-companion#29]
I was able to run the AppImage version but it would be really nice if this could be installed as a flatpak, even better if it were on Flathub.

Thank you!

**Comment by iongion** [comment]
My plan is to only support `flatpak` at a point, the amount of bundle formats is really hard to deal with and it takes a lot of resources.

Most likely next release will have full `flatpak` support

**Comment by sebasmonia** [comment]
If it is planned, feel free to close this issue.

**Comment by sanecito** [comment]
Best to keep this issue open until Flatpak support is released. That way those tracking this issue get pinged when this issue is closed because said release has happened and they can go off and add the source (e.g. Flathub) to their package manager

**Comment by iongion** [comment]
Sure, I'll keep it open, just made it able to build

- https://github.com/iongion/podman-desktop-companion/blob/main/src/app/electron-builder.yml#L14

**Comment by iongion** [comment]
Here it is, initial flatpak support

https://github.com/iongion/podman-desktop-companion/releases/tag/4.0.3-rc.2

Not yet on flathub as I need more testing, it would be really helpful if you could give it a shot.

**Comment by sanecito** [comment]
Done some basic testing on Fedora Kinoite 35. Prompt to create container works in terminal. Container instantly shows up in GUI. Able to delete containers and images from GUI. Able to create and delete Secrets and Volumes. Only thing that doesn't seem to work is Create Machine.

**Comment by sebasmonia** [comment]
Tested in Silverblue, everything seems to work ok on initial testing (including listing images, which didn't work in the previous release).

Will try to use some more today!

**Comment by iongion** [comment]
Closing this - feel free to re-open, maybe open one with publishing to flatpak hub :)
