### ISSUE TITLE
podman-remote unavailable

### ISSUE THREAD

**Issue by NPhMKgbDNy1M** [iongion/podman-desktop-companion#35]
Hello.
I installed podman-desktop-companion on windows. How to use 'Podman Remote'?

![grafik](https://user-images.githubusercontent.com/101069065/163671476-cc251336-4b51-4f7a-b507-b95c91234b6b.png)

**Comment by iongion** [comment]
That feature is @wip - still figuring out

**Comment by gatesry** [comment]
@iongion - Thank you for your work on this project! Anything the community can do to assist in the podman remote connection? Curious what roadblocks you've encountered thus far.

**Comment by iongion** [comment]
The roadblock is actually that I try to support them all at once for all engines, docker included.
Might release podman before docker. Nice thing with podman is that it has remote connections support built-in, while docker will need some ssh tunneling. It is in progress!

**Comment by gatesry** [comment]
Thanks for the update, Ionut. Let me know if I can help with testing in any capacity.

**Comment by RhavinX** [comment]
@iongion Do you have any update as to your progress on remote connections?

**Comment by zackman0010** [comment]
@iongion I'd also like to hear an update, if any!

**Comment by skewty** [comment]
It would seem this project is dead.

**Comment by mailinglists35** [comment]
> Of course it is not @skewty - but I have a life too, feel free to contribute, that would be appreciated. The amazing podman team has spawned an official cross-platform UI, give it a try if this one does not fit your needs https://podman-desktop.io/

no words on remote feature in their client. installed and indeed there is only local support

from their website as well: "Podman Desktop is an open source graphical tool enabling you to seamlessly work with containers and Kubernetes from your **local environment**."

**Comment by iongion** [comment]
Added SSH connection support in current main branch, it will show up in next release.
