### ISSUE TITLE
Hidpi support? 300% scaling small text

### ISSUE THREAD

**Issue by 24fpsDaVinci** [iongion/podman-desktop-companion#36]
Text is very small when gnome is at 300% scaling. some 13" 4k laptops require 300% scaling.
gnome 42, fedora 36 beta

**Comment by iongion** [comment]
Can you try something like this (play with the value, higher means larger fonts):

- for AppImage - `./podman-desktop-companion-x86_64-4.0.3-rc.2.AppImage --force-device-scale-factor=3.0`
- for `rpm` - `/opt/Podman Desktop Companion/podman-desktop-companion --force-device-scale-factor=3.0` 

Respecting the guide from here https://wiki.archlinux.org/title/HiDPI#Electron - I am yet to find a way to set it from the app itself and expose an UI for it.

**Comment by iongion** [comment]
Closing this for now, but feel free to re-open if the method above doesn't help.
I will add it to Known issues
