### ISSUE TITLE
Support for Apple Silicon

### ISSUE THREAD

**Issue by slalabs** [iongion/podman-desktop-companion#37]
The App is not compiled for Apple Silicon or as universal binary for macOS. It only works with Rosetta 2

**Comment by dvaldivia** [comment]
Latest release doesn't even open on Apple Silicon 
```
Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Applications/Podman%20Desktop%20Companion.app/Contents/, NSFilePath=/Applications/Podman Desktop Companion.app/Contents/PlugIns, NSUnderlyingError=0x13dd38a10 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

**Comment by iongion** [comment]
Can you try this https://github.com/iongion/podman-desktop-companion/releases/download/4.0.3-rc.2/podman-desktop-companion-arm64-4.0.3-rc.2.dmg

**Comment by iongion** [comment]
Released `4.0.3-rc.3` that should include Apple cpu support - see the homepage https://iongion.github.io/podman-desktop-companion or directly https://github.com/iongion/podman-desktop-companion/releases/download/4.0.3-rc.3/podman-desktop-companion-arm64-4.0.3-rc.3.dmg

**Comment by iongion** [comment]
Closing this for now, feel free to re-open, I was able to build for Apple CPU, but don't have a device to test, I assume it should be ok.

**Comment by slalabs** [comment]
Sorry I was on vacation. The build works just fine, thanks!
