### ISSUE TITLE
should add rpm spec file to repo

### ISSUE THREAD

**Issue by joequant** [iongion/podman-desktop-companion#40]
would like to package this on mageia but need spec file to be added to repo

**Comment by iongion** [comment]
I don't know what that thing is, I have very shallow understanding of deb packages only.
I just rely on electron-builder to do the work, they have these sections dedicated to the process

- <https://www.electron.build/configuration/linux>
- apparently this other tool is used by electron-builder itself <https://fpm.readthedocs.io/en/latest/cli-reference.html>

All this Linux packaging is such a pain and nothing works, everyone wants to do it his way, no respect for backwards compatibility, no unified format which turns into a horrible user experience.

Feel free to re-open anytime if you find something I can help with.
