### ISSUE TITLE
[feature request] Arch Linux Release via AUR 

### ISSUE THREAD

**Issue by cocoonkid** [iongion/podman-desktop-companion#42]
https://wiki.archlinux.org/title/PKGBUILD

from [Stackexchange - [Installing a .deb package on Arch - Is it possible?](https://unix.stackexchange.com/questions/83540/installing-a-deb-package-on-arch-is-it-possible)

> Not the recommended way (possibly dangerous)
> This method attempts to install the package using the debian packaging format on Arch, which is not recommended due to possible danger of corrupting your installation. If using this method it is recommended to be ready with a rescue disc image of Arch & backup of the user data/space.

This would  be highly appreciated.

**Comment by iongion** [comment]
Sure, I will have a look, but you can try to give `flatpak` a chance, I use Manjaro most of the time and Fedora.
My experience so far with `flatpak` is that desktop integration support is great on both distributions and the world is kind of moving towards this format. This in combination with [Flatseal](
https://github.com/tchx84/Flatseal) is "the future" :)


It is beyond painful to support so many packaging systems, they consume so many resources, no matter the automation.
I am grateful to `electron-builder` team, they make it easy, but still, it is exhausting to test so many.

From developer's experience and resources use, `AppImage` is by far the best, I do am aware of the perception towards its security model, just that at least for evaluation and testing it is a perfect format.

**Comment by cocoonkid** [comment]
Thanks for taking the time to look into it. Actually electron supports  pacman as output so it's not that much of a step to add a AUR repo. I think I myself could actually also work on this.

I personally dislike flatpak a lot but I will look into it once more since I might misjudge this ;-)

I just feel that with flatpak and appimage I need to take care of just another way  keep my applications in order and updated.

**Comment by iongion** [comment]
Solved in https://github.com/iongion/podman-desktop-companion/releases/edit/5.2.0-rc.3
