### ISSUE TITLE
Podman 4.0.3 on Windows Named Pipe Issue

### ISSUE THREAD

**Issue by theonewolf** [iongion/podman-desktop-companion#47]
My `podman` defaults to setting up a `docker_engine` Named Pipe on Windows, not a machine-based Named Pipe.

Podman is resolving this, but it is not released yet: https://github.com/containers/podman/pull/13655

It would be nice if we could _specify_ the Named Pipe to connect to.

**Comment by iongion** [comment]
Hi @theonewolf - thanks for the report, I am planing a re-architecture of all connection management, evaluating

- connect using a custom string
- connect using remote connections
- simultaneous combined connections
- consume the familiar API for as long as `libpod` will follow it

**Comment by iongion** [comment]
What do you think :smile_cat: 

![image](https://user-images.githubusercontent.com/867609/164909509-dc062259-ad2f-476a-aa66-31573d860ea1.png)

**Comment by iongion** [comment]
Just released in `4.0.3-rc5`  https://github.com/iongion/podman-desktop-companion/releases/tag/4.0.3-rc.5
