### ISSUE TITLE
UI freezes on Start a new container 

### ISSUE THREAD

**Issue by austincunningham** [iongion/podman-desktop-companion#49]
# Issue
GUI v4.0.3-rc.3.p   /  CLI podman 3.4.2

- select `Images`
- select `Start` on an image
- adjust some of the setting in `Start a new container` panel 
![start-a-new-container](https://user-images.githubusercontent.com/16667688/164444418-e5f2d217-d128-4687-a24b-279d817bd35d.gif) 
- appears to freeze , UI unresponsive

## System Info
![system-info](https://user-images.githubusercontent.com/16667688/164445383-1035e5cb-3f19-46bc-bf82-127b41f6dfaa.png)

**Comment by iongion** [comment]
Addressed in last merge, thank you, it was an awful one, I am sorry!
Will create new bundles later today after I do tests on all environments

**Comment by iongion** [comment]
Solved in `v4.0.3-rc.4` just released - https://github.com/iongion/podman-desktop-companion/releases/tag/4.0.3-rc.4

**Comment by austincunningham** [comment]
Awesome thanks, Confirmed works as expected , fyi link on https://iongion.github.io/podman-desktop-companion/ still pointing at rc3
