### ISSUE TITLE
Unable to connect via tcp

### ISSUE THREAD

**Issue by Guddiny** [iongion/podman-desktop-companion#55]
![image](https://user-images.githubusercontent.com/16209082/166209903-924f4b18-8f51-4e12-8869-0051270ee6d4.png)

![image](https://user-images.githubusercontent.com/16209082/166209998-177084e7-792c-4e79-9a40-f571a2a6d860.png)

**Comment by iongion** [comment]
Hi @Guddiny  - soon, only unix socket paths are supported for now.
