### ISSUE TITLE
podman machine not running in UI

### ISSUE THREAD

**Issue by rtritto** [iongion/podman-desktop-companion#58]
## Steps to reproduce
Run from a Windows terminal:
`podman machine list`

```console
NAME                     VM TYPE     CREATED        LAST UP            CPUS        MEMORY      DISK SIZE
podman-machine-default*  wsl         8 minutes ago  Currently running  16          640.4MB     737.1MB
```

From Podman Desktop Companion go to Machines tab:
```console
Name                     VM Type     Active         Running            Last Up            Created
podman-machine-default   wsl         Yes            No                 8 minutes ago      true
```

## Actual
Running is _No_ and can't open terminal console

## Expect
Running is _Yes_ and can open terminal console

## Versions
OS: Windows 11
podman: 4.1.0
Podman Desktop Companion: 4.0.3-rc5
---
_Note_: could include all infos (CPUs, Memory, Disk Size etc)

**Comment by iongion** [comment]
I think I fixed this in next release - as for the terminal, sorry, it never worked on windows.
In next release I finally added it, it will support only Windows Terminal opening as new tabs, no ancient shell :1234:

**Comment by iongion** [comment]
See https://github.com/iongion/podman-desktop-companion/releases/tag/4.1.0-rc.9
