### ISSUE TITLE
Unable to choose "Path to podman program"

### ISSUE THREAD

**Issue by dserodio** [iongion/podman-desktop-companion#61]
I installed podman via [Homebrew](https://brew.sh/), which installs it in `/opt/homebrew/bin/podman`. When I open Podman Desktop Companion, it shows /usr/local/bin/podman. I can't choose the correct path using the Select button: I choose the correct path but my selection is ignored.

https://user-images.githubusercontent.com/233589/167420113-e9b76ff7-e1ef-4859-b81f-9e49f18d7bbb.mov

**Comment by iongion** [comment]
Thanks, I've solved them all in the current PR, it is going to deal with it, I release tomorrow.

**Comment by iongion** [comment]
Feature has been added to https://github.com/iongion/podman-desktop-companion/releases/tag/4.1.0-rc.9
