### ISSUE TITLE
[feature] Update version of app

### ISSUE THREAD

**Issue by rtritto** [iongion/podman-desktop-companion#65]
Add a selective option (I think enabled by default) that checks, on startup, if a new version of app is available.
Then show a popup (to choose if update) or show in UI (to update manually) or other.

**Comment by iongion** [comment]
Yes, this is probably now as important as adding testing everywhere.
It is extremely tedious to quickly deploy fixes, wait for builds.

Electron has a facility to auto-update, but considering there are deployment formats for distributions, one wouldn't prefer code swapping just like that, needs a good approach.

Of course, starting at least with a minimal "there is an update" should be the way

**Comment by iongion** [comment]
Added in current main branch, solved!

![image](https://github.com/user-attachments/assets/f598699e-c702-4d5d-8035-17e2d2583755)
