### ISSUE TITLE
"Path to native podman CLI" disappears after saving

### ISSUE THREAD

**Issue by dserodio** [iongion/podman-desktop-companion#73]
I type the path do my podman CLI, and when I hit Save, it disappears. Is this expected?

https://user-images.githubusercontent.com/233589/167876711-b45368d7-e73a-4af1-a0b2-eeaa7ed90055.mov

Note: I had typed both "Path to native podman CLI" and "Connection string" and saved since they weren't auto-detected.

I should note that I don't know that to do after this. I can't see any other screens on this app other than this initial settings screen, so the app is unable for me at the moment.

**Comment by iongion** [comment]
Awesome report - no, it is not ok that it does not save, it is a bug! At least is not crashing and I might be able to finally know why it does it for so many users.

Can you try to upload the logs ?

You can also try to click connect after you type the path and see if it does connect

**Comment by PyPandaPo** [comment]
does not connect
<img width="869" alt="image" src="https://user-images.githubusercontent.com/97765953/167896594-5d8c8142-db92-4119-8784-6753bbf957e6.png">

**Comment by iongion** [comment]
Thank you, those errors are expected. I've just release the 4.1.0-rc.10 above -it should be able to deal with both saving and connecting.

If still having issues, you can set the logs to `Debug` , restart and see more info - my podman on mac is in `/usr/local/bin/podman` as I think I did a brew link podman at a point

**Comment by PyPandaPo** [comment]
@iongion in the screenshots version 4.1.0-rc.10 with Debug mode

**Comment by iongion** [comment]
Have you already performed `podman machine init` ?

**Comment by PyPandaPo** [comment]
yes

**Comment by PyPandaPo** [comment]
<img width="1703" alt="image" src="https://user-images.githubusercontent.com/97765953/167899366-786b65fa-3cce-4dd4-93ca-8d008f473bd8.png">

my podman version
<img width="225" alt="image" src="https://user-images.githubusercontent.com/97765953/167899504-64f68442-de94-4f27-a49b-edba284e8074.png">

**Comment by iongion** [comment]
Huge thanks  - I was able to reproduce also

![image](https://user-images.githubusercontent.com/867609/167899462-8d013d64-78c4-4702-8a79-3efd957bf304.png)

**Comment by iongion** [comment]
Done, I think I've found it with your awesome help - THANK YOU! `rc.11` is building

**Comment by iongion** [comment]
While I fix it, you could try to install `lima` just to have the cli available `brew install lima` and see if the app starts, this was it. That exception was preventing the entire startup.

**Comment by PyPandaPo** [comment]
installing `lima` did not help

**Comment by iongion** [comment]
Uploading dmg files right now https://github.com/iongion/podman-desktop-companion/releases/edit/4.1.0-rc.11

**Comment by iongion** [comment]
Damn, thank you the same, truly helpful, imagine it now solves for all users.

**Comment by dserodio** [comment]
Unfortunately, saving still doesn't for for me using 4.1.0-rc.11
Now it reverts back to `/usr/local/bin/podman` which is the default instead of just disappearing.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/233589/167949458-f0e53c0c-44be-4c3a-bdff-d145e1c2fdc7.png">

**Comment by iongion** [comment]
I see the `podman machines` list is empty, it could be a chicken or the egg problem - to get the list, one needs to set the program, to save, one needs both :)

I am going to replicate the same homebrew setup as yours and see what is going on

**Comment by iongion** [comment]
I solved it here I think, in next unreleased v12 https://github.com/iongion/podman-desktop-companion/issues/64

**Comment by iongion** [comment]
Solved in https://github.com/iongion/podman-desktop-companion/releases/edit/4.1.0-rc.21 - re-open if not the case
