### ISSUE TITLE
Missing `podman-machine-default` machine

### ISSUE THREAD

**Issue by rtritto** [iongion/podman-desktop-companion#77]
![image](https://user-images.githubusercontent.com/40242971/167956798-ae42ede9-702c-47bf-b9b6-ea2556bbaefd.png)

## Expected
```console
Name                     VM Type     Active         Running            Last Up            Created
podman-machine-default   wsl         Yes            Yes                8 minutes ago      true
```

## Versions
OS: Windows 11
podman: 4.1.0
Podman Desktop Companion: 4.1.0-rc12

**Comment by iongion** [comment]
Confirmed, fix upcoming

**Comment by iongion** [comment]
Solved in https://github.com/iongion/podman-desktop-companion/releases/edit/4.1.0-rc.21 - re-open if not the case
