### ISSUE TITLE
Upload to flathub

### ISSUE THREAD

**Issue by skymoo** [iongion/podman-desktop-companion#89]
As mentioned in #29 this is a request to track uploading the flatpak to flathub.

**Comment by iongion** [comment]
did not forget it, will deal with it at a moment - some bugs to fix

**Comment by gasinvein** [comment]
Note that Flathub requires all apps to be built offline. There are tools to help achieving this with node/electron apps, but still the workflow differs significantly from outputting `.flatpak` bundles with electron-builder. Please let me know if you need any help with building the app for Flathub.

But before proceeding, please consider switching to Yarn. It has overall much better support for offline and deterministic builds.

**Comment by iongion** [comment]
Thanks @gasinvein - just moved all to yarn - I am currently trying migration to vitejs of everything using this awesome project template https://github.com/cawa-93/vite-electron-builder

**Comment by gasinvein** [comment]
That template seems to directly call `npm` from `package.json` scripts. Are you planning to migrate to it from python-invoke as well?

**Comment by iongion** [comment]
If I will be able to avoid writing kilometers of "package.json" scripts to do what invoke does, of course. I would try and make-it as node-ish as possible.

**Comment by iongion** [comment]
Added templates to publish anywhere electron-builder supports it - but someone needs to take over this.

**Comment by iongion** [comment]
Opened a ticket for this - see here https://github.com/iongion/container-desktop/issues/166
