### ISSUE TITLE
Add to Winget

### ISSUE THREAD

**Issue by Danik1601** [iongion/podman-desktop-companion#90]
I decided that you would be happy to have another open ticket to cause you a headache up until the release.
This one is to track Podman Desktop Companion availability in Microsoft's [Windows Package Manager](https://docs.microsoft.com/en-us/windows/package-manager/) "Winget" repository that is available for Windows 10 (1809) and up

**Comment by iongion** [comment]
Unfortunately at this moment, I don't have the budget for performing code signing as it requires payment. I've added the manifests for whoever is financially and technically savy to join in and do it, see in <https://github.com/iongion/podman-desktop-companion/tree/main/support/winget>
