### ISSUE TITLE
WSL2 - Unable to find podman CLI in <Distribution>

### ISSUE THREAD

**Issue by derkoe** [iongion/podman-desktop-companion#93]
Podman desktop companion cannot find podman CLI in WSL2

![image](https://user-images.githubusercontent.com/123199/170992016-bc27b2d4-ba61-4c56-8a6c-8935812c2e61.png)

Error in console
```
model.ts:176 Error during connection string test Error: opts is not defined
```

podman is installed in the Distro
```
❯ wsl -d Fedora podman version
Version:      3.4.7
API Version:  3.4.7
Go Version:   go1.16.15
Built:        Thu Apr 21 15:14:26 2022
OS/Arch:      linux/amd64
```

**Comment by iongion** [comment]
Confirmed, thanks!

**Comment by iongion** [comment]
Solved it, will release soon - also planning to cover all that part with tests before migrating to typescript. It is a class of errors that typescript would just shine preventing. I just had not time to setup a pipeline for it!

**Comment by iongion** [comment]
Present in current main branch - solved
