### ISSUE TITLE
System try icon on windows very small

### ISSUE THREAD

**Issue by geertschuring** [iongion/podman-desktop-companion#94]
The system tray icon on windows seems to be much smaller then it needs to be:

![afbeelding](https://user-images.githubusercontent.com/598355/171642514-645c64fb-9f7f-48c1-bc56-9105d9d6683d.png)

Compared to the docker icon its noticeably smaller.

**Comment by iongion** [comment]
Yup, that was a hasty one :) - Better monochrome or duotone icons, thanks for the example!

**Comment by iongion** [comment]
![image](https://github.com/user-attachments/assets/9388d33e-f52a-4e64-8ce3-b10e2ace0b9b)

Hopefully better, not that happy myself with it, feel free to re-open.
