### ISSUE TITLE
Using with podman in Ubuntu 22.04 WSL2 on Windows

### ISSUE THREAD

**Issue by mtcolman** [iongion/podman-desktop-companion#95]
Hi, I've installed 4.1.0-rc.28.p on Windows 10 (Version 21H2 (OS Build 19044.1706)) and I'm trying to run with Ubuntu (22.04) WSL2 (I am also experiencing the same issue with Ubuntu 20.04). The UI is telling me it can find the podman CLI (`/usr/bin/podman/`), but when I test the connection string (`/tmp/podman-desktop-companion-podman-rest-api.sock`) it fails, telling me "API could not be reached". The UI also states "Unusable connection".

I couldn't see any installation instructions to know if I've done something wrong/not done all steps I needed to/have missed some system requirements. If I try clicking on "Connect" it times out after a while of attempting somthing...

![image](https://user-images.githubusercontent.com/33348891/172011265-75bc00d8-1d5e-4ecf-ac25-4a5f3a6bbfe2.png)

Thanks in advance for any assistance.

**Comment by mtcolman** [comment]
Update: I have managed to overcome the issue on Ubuntu 20.04 by installing `socat` (using `sudo apt install socat -y`).

**Comment by mtcolman** [comment]
This was the error I saw on 20.04:
```
17:02:37.375 › C:\Windows\System32\wsl.exe --distribution Ubuntu-20.04 printf GET /v3.0.0/libpod/_ping HTTP/1.1
Accept: application/json
Content-Type: application/json
User-Agent: axios/0.25.0
Host: localhost
Connection: close

 | socat UNIX-CONNECT:/tmp/podman-desktop-companion-podman-rest-api.sock - spawning stderr /bin/bash: line 7: socat: command not found
```

And I've just seen this on 22.04:
```
17:05:30.251 › C:\Windows\System32\wsl.exe --distribution Ubuntu-22.04 /usr/bin/podman --version spawning stderr time="2022-06-04T17:05:30+01:00" level=error msg="mkdir /home/matt/rundir/libpod: no such file or directory"

17:05:55.922 › C:\Windows\System32\wsl.exe --distribution Ubuntu-22.04 /usr/bin/podman --version spawning stderr time="2022-06-04T17:05:55+01:00" level=error msg="failed to create temp directory for user: mkdir /tmp/containers-user-1000: permission denied"
```

For which I've manually done:
```
mkdir -p /home/matt/rundir/libpod
sudo mkdir -p /tmp/containers-user-1000
```

**Comment by mtcolman** [comment]
I've done a further test, changing the connection string, to see whether desktop companion tries connecting to Ubuntu-22.04 when instructed, however I can see, as per screenshot, it is connecting to Ubuntu-20.04 regardless:
![image](https://user-images.githubusercontent.com/33348891/172016202-f7434cd5-340c-4e7e-80bf-053df2cfa79c.png)

**Comment by mtcolman** [comment]
Further to this, I've also got trivy installed:
```
$ trivy -v
Version: 0.28.1
$ command -v trivy
/usr/local/bin/trivy
```

And yet the UI is showing:
![image](https://user-images.githubusercontent.com/33348891/172016683-843260d6-d2a8-4b61-80cc-657d10346352.png)

**Comment by iongion** [comment]
I am so happy you found your a way with `socat`!
It will definitely be improved soon, the soft side, documentation, tutorials.
I am preparing a final release for what means features, it also solves most of the bugs reported by users so far.

Once that is done, the focus will only be

* deployment - proper binaries, digitally signed for both windows + mac, flatpak hub, rpm-spec (winget, home-brew)
* documentation

Thank you for the bug report with the scanner not being found, it actually expects a windows native binary for scanner, but I will try to handle the case you reported too.

**Comment by mtcolman** [comment]
@iongion thanks for your response. It would be great if it could handle a linux installed Trivy.

Also, any thoughts on why Ubuntu-22.04 wasn't be referenced even when selected, and instead 20.04 is used as the version?

Thanks!

**Comment by mmurhamm** [comment]
I am using podman in a Fedora WSL2 distro () because I could not get podman 4 installed into my Ubuntu 22.04 WSL2 distro. The podman desktop runs fine with it. Connection strings are as follows:
![Screenshot 2022-06-07 132224](https://user-images.githubusercontent.com/50318653/172367772-74cb2f49-3529-4266-a95e-96aa25f77ebf.png)
As for trivy, that is not showing anything on Windows because there is no link back to the WSL2 distro where trivy would run; maybe we can integrate it via a client/server deployment of trivy?

**Comment by iongion** [comment]
Give the 5.x series a chance, maybe this is solved. The amount of configuration possibilities is too high for me to test them all. Feel free to re-open if needed.
