### ISSUE TITLE
Different UI and cannot use remote

### ISSUE THREAD

**Issue by lystormenvoy** [iongion/podman-desktop-companion#96]
![image](https://user-images.githubusercontent.com/6795312/172570041-fda45334-259d-4c90-ac41-0ed3b2f3a44c.png)

I install on Windows 11.
I down the installer exe from https://iongion.github.io/podman-desktop-companion/
After install  and run, I found the UI is different from the picture on website. And the connection type - Remote  could not be selected.
How to resolve?

**Comment by gatesry** [comment]
The pictures seen on the readme page were from a previous version. Regarding the `Remote` podman connection, this is still being worked on. #35

**Comment by iongion** [comment]
Sorry and thanks @gatesry - will update video and Remote support at next release

**Comment by lystormenvoy** [comment]
Thanks

**Comment by iongion** [comment]
I keep it open, helps me track the video update that I forgot about, also thanks for caring!

**Comment by bnaambo** [comment]
hi the remote feature is still in work? greetings from Kenya

**Comment by iongion** [comment]
Solved in current main branch, will appear in next release
