### ISSUE TITLE
trivy scan results

### ISSUE THREAD

**Issue by mtcolman** [iongion/podman-desktop-companion#98]
Hi, just wanted to drop some feedback (great tool by the way). I've managed to take a look at the Trivy scanning results you provide, as per this image (for an Ubuntu container): 
![image](https://user-images.githubusercontent.com/33348891/173189598-a5d1f95f-d304-4373-a43e-22a40ea3c53c.png)

Have you elected to not show the "low" vulnerabilities summary at the top of the screen on purpose? Otherwise, I think it would be useful to a) show it; or b) provide an option to the user to allow them to select which levels of vulnerability to view.

Back to my main point, I've performed the same Ubuntu scan from the command line and I get the format:
![image](https://user-images.githubusercontent.com/33348891/173189671-ebe1c047-5ad4-4089-a0b9-cc294bd17c12.png)

which helpfully shows me which package/library, the installed version and if applicable, the version the vulnerability is fixed in. For me, these are particularly helpful columns to have access to (along with CVE number). Is there anyway these could be surfaced to the podman desktop companion UI? It could also be useful to permit the user to select which columns they wish to view?

Thanks!

**Comment by iongion** [comment]
Hopefully solved in [5.2.0-rc.3](https://github.com/iongion/podman-desktop-companion/releases/tag/5.2.0-rc.3), re-open if needed.
